version: "3.7"
services:
 db:
   image: "mysql:5.7"
   environment:
     MYSQL_ROOT_PASSWORD: 123456
     MYSQL_USERNAME: barakat
     MYSQL_PASSWORD: 123456
   ports:
      - "3307:3306"
 redis:
   image: "redis:4.6.0"
   command: redis-server
   volumes:
      - "redis:/data"

 website:
   depends_on:
      - "db"
      - "redis"
   build: .
   ports:
      - "3000:3000"
   environment:
     DB_USERNAME: root
     DB_PASSWORD: root
     DB_DATABASE: sample
     DB_PORT: 3306
     DB_HOST: db
     RAILS_ENV: production
     RAILS_MAX_THREADS: 5
   volumes:
      - ".:/app"
      - "./config/docker/database.yml:/app/config/database.yml"

 sidekiq:
   depends_on:
      - "db"
      - "redis"
   build: .
   command: sidekiq -C config/sidekiq.yml
   volumes:
      - ".:/app"
   environment:
     REDIS_URL: redis://redis:6379/0

volumes:
 redis:
 db: